In [2]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
from sklearn.metrics import mean_absolute_error

In [3]:
kowope_data_filepath = './DSN_DATASET/Train.csv'
kowope_data = pd.read_csv(kowope_data_filepath)
kowope_data.head()

,Applicant_ID,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,...,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50,default_status
0,Apcnt_1000000,3436.0,0.28505,1.6560,0.0,0.000,0.0,10689720.0,252072.0,4272776.0,...,0.392854,2.02,0.711632,0.0,0.0,charge,NaN,1.129518,0.044335,no
1,Apcnt_1000004,3456.0,0.67400,0.2342,0.0,0.000,0.0,898979.0,497531.0,9073814.0,...,0.314281,8.08,0.183584,NaN,0.0,charge,349.805730,1.620483,0.322436,no
2,Apcnt_1000008,3276.0,0.53845,3.1510,0.0,6.282,NaN,956940.0,NaN,192944.0,...,0.162965,18.18,0.791136,0.0,0.0,charge,NaN,1.513370,0.011640,yes
3,Apcnt_1000012,3372.0,0.17005,0.5050,0.0,0.000,192166.0,3044703.0,385499.0,3986472.0,...,0.488884,2.02,0.685168,NaN,0.0,charge,89.940100,0.664452,0.082729,no
4,Apcnt_1000016,3370.0,0.77270,1.1010,0.0,0.000,1556.0,214728.0,214728.0,1284089.0,...,0.275000,12.12,0.438168,0.0,0.0,charge,97.887502,1.427891,0.045630,no

In [4]:
y = kowope_data["default_status"].replace({"yes": 1, "no": 0})
# df["column1"].replace({"a": "x", "b": "y"}, inplace=True)
y[:5]

0    0
1    0
2    1
3    0
4    0
Name: default_status, dtype: int64

In [5]:
features = ['form_field1','form_field2','form_field3','form_field4','form_field5','form_field6','form_field7','form_field8','form_field9',
            'form_field10','form_field11','form_field12','form_field13','form_field14','form_field15','form_field16','form_field17',
            'form_field18','form_field19','form_field20','form_field21','form_field22','form_field23','form_field24','form_field25',
            'form_field26','form_field27','form_field28','form_field29','form_field30','form_field31','form_field32','form_field33',
            'form_field34','form_field35','form_field36','form_field37','form_field38','form_field39','form_field40','form_field41',
            'form_field42', 'form_field43', 'form_field44', 'form_field45', 'form_field46', 'form_field48', 'form_field49']
X = kowope_data[features]
len(X)

56000

In [6]:
X = X.fillna(X.mean())
X

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,...,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field48,form_field49
0,3436.0,0.28505,1.6560,0.0000,0.000,0.000000,10689720.0,2.520720e+05,4.272776e+06,11333126.0,...,0.0,147.797977,108.117363,0.392854,2.02,0.711632,0.00000,0.000000,305244.932775,1.129518
1,3456.0,0.67400,0.2342,0.0000,0.000,0.000000,898979.0,4.975310e+05,9.073814e+06,2533168.0,...,0.0,147.797977,108.117363,0.314281,8.08,0.183584,0.07252,0.000000,349.805730,1.620483
2,3276.0,0.53845,3.1510,0.0000,6.282,624447.924437,956940.0,2.626690e+06,1.929440e+05,1079864.0,...,0.0,149.680500,108.117363,0.162965,18.18,0.791136,0.00000,0.000000,305244.932775,1.513370
3,3372.0,0.17005,0.5050,0.0000,0.000,192166.000000,3044703.0,3.854990e+05,3.986472e+06,3621979.0,...,1.0,147.797977,108.117363,0.488884,2.02,0.685168,0.07252,0.000000,89.940100,0.664452
4,3370.0,0.77270,1.1010,0.0000,0.000,1556.000000,214728.0,2.147280e+05,1.284089e+06,361770.0,...,0.0,150.013500,108.117363,0.275000,12.12,0.438168,0.00000,0.000000,97.887502,1.427891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55995,3740.0,0.01730,0.0000,0.0000,0.000,770998.000000,9637475.0,4.047934e+06,1.164199e+07,19910965.0,...,0.0,147.797977,108.117363,0.000000,9.09,0.730040,0.07252,0.000000,591.048913,0.000000
55996,3360.0,2.01145,0.6252,0.0000,0.000,624447.924437,927765.0,2.626690e+06,1.316002e+07,1849306.0,...,0.0,158.025000,136.513500,0.297913,30.30,0.498208,0.07252,0.000000,305244.932775,0.000000
55997,3500.0,0.76640,0.0000,0.0000,0.000,118645.000000,3662435.0,3.662435e+06,3.585024e+06,704090.0,...,0.0,147.797977,108.117363,0.550000,3.03,0.450512,0.00000,0.000000,1252.474467,2.000000
55998,3280.0,0.05235,2.0916,2.2212,0.000,624447.924437,3458599.0,2.626690e+06,1.155330e+05,3458599.0,...,1.0,147.797977,150.000000,0.942854,0.00,0.705048,1.00000,0.000000,305244.932775,0.000000
55999,3522.0,0.46930,0.0000,0.0000,0.000,98806.000000,2053920.0,5.239830e+05,1.490337e+07,5430440.0,...,0.0,147.797977,108.117363,0.000000,13.13,0.292424,0.07252,0.095371,4986.188578,3.000000

In [17]:
from sklearn.impute import SimpleImputer

X = kowope_data[features]

# getting columns with missing values
cols_with_missing = [col for col in X.columns
                     if X[col].isnull().any()]

# Make copy to avoid changing original data (when imputing)
X_plus = X.copy()
X_valid = test_data[features].copy()

# Make new columns indicating what will be imputed
for col in cols_with_missing:
    X_plus[col + '_was_missing'] = X_plus[col].isnull()
    X_valid[col + '_was_missing'] = X_valid[col].isnull()

# Imputation
my_imputer = SimpleImputer()
imputed_X_plus = pd.DataFrame(my_imputer.fit_transform(X_plus))
imputed_valid = pd.DataFrame(my_imputer.transform(X_valid))

# Imputation removed column names; put them back
imputed_X_plus.columns = X_plus.columns
imputed_valid.columns = X_valid.columns

print(len(imputed_valid.columns))
print(len(imputed_X_plus.columns))

95
95

In [15]:
# define and fit the model
kowope_model = RandomForestClassifier(n_estimators=100, criterion='entropy',random_state=1)
kowope_model.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [7]:
test_filepath = './DSN_DATASET/Test.csv'
test_data = pd.read_csv(test_filepath)
test_data[:5]

,Applicant_ID,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,...,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50
0,Apcnt_1000032,3236.0,0.34875,10.2006,0.0000,0.0,418564.0,418564.0,418564.0,540710.0,...,NaN,0.825000,1.01,0.800000,NaN,0.0,charge,NaN,0.000000,0.011221
1,Apcnt_1000048,3284.0,1.27360,2.9606,9.0198,0.0,0.0,9858816.0,49014.0,1510098.0,...,18.8415,0.507694,4.04,0.623248,1.0,0.0,lending,NaN,0.504974,0.043525
2,Apcnt_1000052,NaN,0.27505,0.0600,0.0000,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,0.00,NaN,NaN,NaN,charge,NaN,0.000000,NaN
3,Apcnt_1000076,3232.0,0.28505,2.8032,0.0000,0.0,0.0,473802.0,473802.0,1724437.0,...,NaN,0.916663,2.02,0.464224,NaN,NaN,charge,90.163742,0.788809,0.104029
4,Apcnt_1000080,3466.0,2.09545,0.8318,2.5182,0.0,19839.0,1150662.0,1150662.0,7860523.0,...,NaN,0.234047,23.23,0.726688,0.0,0.0,lending,1303.587148,1.637733,0.163124

In [8]:
val_X = test_data[features]
val_X = val_X.fillna(val_X.mean())

In [9]:
val_X

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,...,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field48,form_field49
0,3236.000000,0.34875,10.2006,0.0000,0.0000,4.185640e+05,4.185640e+05,4.185640e+05,5.407100e+05,0.0,...,0.000000,147.62328,108.209648,0.825000,1.01,0.800000,0.066526,0.000000,301544.001781,0.000000
1,3284.000000,1.27360,2.9606,9.0198,0.0000,0.000000e+00,9.858816e+06,4.901400e+04,1.510098e+06,18308285.0,...,2.000000,147.62328,18.841500,0.507694,4.04,0.623248,1.000000,0.000000,301544.001781,0.504974
2,3492.284404,0.27505,0.0600,0.0000,0.0000,6.263036e+05,6.797033e+06,2.654142e+06,1.350593e+07,0.0,...,0.090749,147.62328,108.209648,0.369684,0.00,0.566219,0.066526,0.097926,301544.001781,0.000000
3,3232.000000,0.28505,2.8032,0.0000,0.0000,0.000000e+00,4.738020e+05,4.738020e+05,1.724437e+06,493641.0,...,0.000000,147.62328,108.209648,0.916663,2.02,0.464224,0.066526,0.097926,90.163742,0.788809
4,3466.000000,2.09545,0.8318,2.5182,0.0000,1.983900e+04,1.150662e+06,1.150662e+06,7.860523e+06,5752921.0,...,0.000000,147.62328,108.209648,0.234047,23.23,0.726688,0.000000,0.000000,1303.587148,1.637733
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23995,3258.000000,0.37925,0.5698,5.1282,0.0000,6.263036e+05,2.280318e+06,2.654142e+06,1.350593e+07,2280318.0,...,0.000000,147.62328,92.691000,1.100000,0.00,0.800000,0.066526,1.000000,301544.001781,0.000000
23996,3514.000000,0.95260,0.0000,0.0000,0.0000,1.494538e+06,4.773419e+06,4.773419e+06,8.971857e+07,12999991.0,...,0.000000,147.62328,125.022000,0.000000,12.12,0.196400,0.000000,0.000000,4200.072959,3.000000
23997,3302.000000,0.05755,4.2394,0.0000,25.4376,6.263036e+05,4.940300e+04,2.654142e+06,1.350593e+07,49403.0,...,0.000000,147.62328,108.209648,1.100000,1.01,0.800000,0.066526,0.000000,301544.001781,4.855060
23998,3334.000000,0.75670,1.4428,0.0000,0.0000,0.000000e+00,2.513329e+06,3.773300e+04,3.936680e+05,2551062.0,...,0.000000,147.62328,31.195500,0.440000,2.02,0.519776,0.066526,0.000000,27.325129,0.818733
23999,3324.000000,0.44840,2.3170,6.7176,0.0000,6.263036e+05,5.305182e+06,2.654142e+06,1.888595e+07,5361587.0,...,0.000000,147.62328,112.303500,0.314281,3.03,0.544352,0.000000,1.000000,301544.001781,0.000000

In [19]:
predictions = kowope_model.predict(val_X)

In [21]:
predictions[:20]

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1],
      dtype=int64)

In [11]:
customer_id = test_data['Applicant_ID']
customer_id

0        Apcnt_1000032
1        Apcnt_1000048
2        Apcnt_1000052
3        Apcnt_1000076
4        Apcnt_1000080
             ...
23995     Apcnt_999940
23996     Apcnt_999956
23997     Apcnt_999976
23998     Apcnt_999984
23999     Apcnt_999992
Name: Applicant_ID, Length: 24000, dtype: object

In [19]:
import csv
with open('output5.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Application_ID", "default_status"])
    for i in range(len(pred0)):
        writer.writerow([customer_id[i], pred0[i]])

In [ ]:
from sklearn.metrics import mean_absolute_error
print(predictions, )

In [ ]:
# Save predictions in format used for competition scoring
output = pd.DataFrame({'Id': X_test.index,
                       'SalePrice': preds_test})
output.to_csv('submission.csv', index=False)

In [7]:
kowope_model.score(X, y)

0.9999464285714286

In [ ]:
# using pipline method 
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.model_selection import cross_val_score

my_pipeline = Pipeline(steps=[
    ('preprocessor', SimpleImputer()),
    ('model', RandomForestRegressor(n_estimators=50, random_state=0))
])

# Multiply by -1 since sklearn calculates *negative* MAE
scores = -1 * cross_val_score(my_pipeline, X, y,
                              cv=5,
                              scoring='neg_mean_absolute_error')

print("Average MAE score:", scores.mean())

In [ ]:
# trying out different n_estimators

def get_score(n_estimators):
    """Return the average MAE over 3 CV folds of random forest model.
    
    Keyword argument:
    n_estimators -- the number of trees in the forest
    """
    # Replace this body with your own code
    my_pipeline = Pipeline(steps=[
    ('preprocessor', SimpleImputer()),
    ('model', RandomForestRegressor(n_estimators=n_estimators, random_state=0))
    ])
    scores = -1 * cross_val_score(my_pipeline, X, y,
                              cv=3,
                              scoring='neg_mean_absolute_error')
    return scores.mean()

n_estimators = [50, 100, 150, 200, 250, 300, 350, 400]
results = {} # Your code here
for i in n_estimators:
    results[i] = get_score(i)

In [18]:
from xgboost import XGBClassifier
my_model = XGBClassifier(n_estimators=1000, learning_rate=0.05)
my_model.fit(imputed_X_plus, y, verbose=False)
pred0 = my_model.predict(imputed_valid)